# Google App Engine configuration for DisAID backend
runtime: nodejs18

env: standard

instance_class: F1

automatic_scaling:
  min_instances: 0
  max_instances: 10

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  # Add your environment variables here (or use Secret Manager)
  # MONGODB_URI: "your_mongodb_atlas_connection_string"
  # JWT_SECRET: "your_jwt_secret"
  # GEMINI_API_KEY: "your_gemini_api_key"

handlers:
  - url: /.*
    script: auto
    secure: always

