services:
  # Backend API Service
  - type: web
    name: disaid-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node serverSQLite.js
    envVars:
      - key: PORT
        value: 5001
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
    disk:
      name: sqlite-data
      mountPath: /var/data
      sizeGB: 1
    healthCheckPath: /

  # Frontend Service
  - type: web
    name: disaid-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://disaid-backend.onrender.com/api

